spring.config.import=optional:file:.env[.properties]

spring.application.name=payflow
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${REDIS_LOCALHOST}
spring.data.redis.port=${REDIS_PORT}

spring.data.secretkey.payflow=${SECRET_KEY}

spring.uri.binlist.net=${BINLIST_URI}

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}


